language: node_js
node_js:
  - "5.5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script: npm install && npm run build && npm run test
before_install:
  - pip install codecov
after_success:
  - codecov
