language: node_js
node_js:
  - "5.5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - npm install codecov
before_script:
  - npm run build
after_success:
  - npm run report-coverage
