language: node_js
node_js:
  - "5.5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - npm install codecov
before_script:
  - npm run build
script:
  - npm run test
  - npm run coverage
after_success:
  - npm run report
notifications:
  email: false
